name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u kamble10pratik10-ops --password-stdin

      - name: Build Image
        run: docker build -t ghcr.io/kamble10pratik10-ops/ecoexchange:latest ./backend

      - name: Push Image
        run: docker push ghcr.io/kamble10pratik10-ops/ecoexchange:latest
